### ISSUE TITLE
`track` should be useable without specifying `.system()`

### ISSUE THREAD

**Issue by TheNeikos** [inodentry/bevy_loading#1]
`bevy` has recently switched to using `IntoSystem` so as to allow users to not have to specify `.system` everywhere. I believe that this should be reflected in the `track` function as well and would make it fit more.

**Comment by inodentry** [comment]
Oh yes, that's correct, though AFAIK this is only applicable to bevy main, not 0.5. I originally wrote and tested the plugin with 0.5, and just quickly fixed up compile errors to make the `bevy_main` branch, so that is probably why I missed this.

This is now fixed in the `bevy_main` branch. :slightly_smiling_face: Enjoy!
